server:
  port: 8301
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  security:
    oauth2:
      authorizationserver:
        issuer: http://elementoj-auth
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
#    org.hibernate.SQL: DEBUG
    com.service.policy.mapper: DEBUG
    com.baomidou.example.mapper: DEBUG
    com.chz.mapper: debug

