server:
  port: 8501
spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  security:
    oauth2:
      client:
        default-registration: elementoj-gateway
        registration:
          elementoj-gateway:
            provider: elementoj-auth # 引用 provider 的名称
            client-id: elementoj
            client-secret: elementoj1
            authorization-grant-type: authorization_code
            redirect-uri: "https://www.baidu.com"
            scope: all
        provider:
          elementoj-auth: # 自定义名称，与 registration 中的 provider 对应
            authorization-uri: http://elementoj-auth:8301/oauth2/authorize
            token-uri: http://elementoj-auth:8301/oauth2/token
            user-info-uri: http://elementoj-auth:8301/userinfo
            user-name-attribute: userId


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE