/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./src/components/account/AccountCard.vue')['default']
    BottomLeftMenu: typeof import('./src/components/submit/BottomLeftMenu.vue')['default']
    BottomRightMenu: typeof import('./src/components/submit/BottomRightMenu.vue')['default']
    BottomSubmitSide: typeof import('./src/components/submit/BottomSubmitSide.vue')['default']
    CalendarInfo: typeof import('./src/components/index/CalendarInfo.vue')['default']
    CarouselList: typeof import('./src/components/index/CarouselList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExpostulationCard: typeof import('./src/components/index/ExpostulationCard.vue')['default']
    LeftProblemDetail: typeof import('./src/components/submit/LeftProblemDetail.vue')['default']
    LeftSide: typeof import('./src/components/submit/LeftSide.vue')['default']
    LeftTopMenu: typeof import('./src/components/submit/LeftTopMenu.vue')['default']
    LoginCard: typeof import('./src/components/account/LoginCard.vue')['default']
    NavMenu: typeof import('./src/components/page/NavMenu.vue')['default']
    ProblemActionCard: typeof import('./src/components/problem/ProblemActionCard.vue')['default']
    ProblemCard: typeof import('./src/components/problem/ProblemCard.vue')['default']
    ProblemDetail: typeof import('./src/components/problem/ProblemDetail.vue')['default']
    ProblemListCard: typeof import('./src/components/problem/ProblemListCard.vue')['default']
    ProblemTextCard: typeof import('./src/components/problem/ProblemTextCard.vue')['default']
    ProblemTitle: typeof import('./src/components/problem/ProblemTitle.vue')['default']
    RegisterCard: typeof import('./src/components/account/RegisterCard.vue')['default']
    RelaxButton: typeof import('./src/components/submit/RelaxButton.vue')['default']
    RightSide: typeof import('./src/components/submit/RightSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCaseCard: typeof import('./src/components/problem/TestCaseCard.vue')['default']
    TopSubmitSide: typeof import('./src/components/submit/TopSubmitSide.vue')['default']
    UploadPannel: typeof import('./src/components/index/UploadPannel.vue')['default']
    UserPannel: typeof import('./src/components/page/UserPannel.vue')['default']
    VideoPannel: typeof import('./src/components/index/VideoPannel.vue')['default']
    VideoPlayer: typeof import('./src/components/index/VideoPlayer.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
